# AUKEY WebCam monocular

#==============#
# Camera Model #
#==============#
Camera.name: "AUKEY-WebCam"
Camera.setup: "monocular"
Camera.model: "equirectangular"

## representation 1 - pixel rep. - Victor's original ##
Camera.fps: 30.0
Camera.cols: 1920
Camera.rows: 1080
Camera.fx: 2669.328086
Camera.fy: 2607.600518
Camera.cx: 540.743566
Camera.cy: 249.349171
Camera.k1: 0.283600495266156
Camera.k2: 0.13676501661761326
Camera.p1: -0.02359712114118154
Camera.p2: -0.11152650794623843
Camera.color_order: "RGB"

## Math - don't uncomment, might have to delete ##
# Camera.fps: 30.0
# Camera.cols: 1920 - width
# Camera.rows: 1080 - height
# Camera.fx: 2669.328086 / 1920 =
# Camera.fy: 2607.600518 / 1080 =
# Camera.cx: 540.743566 / 1920 =
# Camera.cy: 249.349171 / 1080 =
# Camera.k1: 0.283600495266156
# Camera.k2: 0.13676501661761326
# Camera.p1: -0.02359712114118154
# Camera.p2: -0.11152650794623843
# Camera.color_order: "RGB"

## representation 2 - factors rep. ##
#Camera.fps: 30.0
#Camera.cols: 1920
#Camera.rows: 1080
#Camera.fx: 1.39027504479
#Camera.fy: 2.41444492407
#Camera.cx: 0.28163727395
#Camera.cy: 0.23087886203
#Camera.k1: 0.283600495266156
#Camera.k2: 0.13676501661761326
#Camera.p1: -0.02359712114118154
#Camera.p2: -0.11152650794623843
#Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer.keyframe_size: 0.05
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.08
PangolinViewer.camera_line_width: 3
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -0.9
PangolinViewer.viewpoint_z: -1.9
PangolinViewer.viewpoint_f: 400
