

#==============#
# Camera Model #
#==============#

Camera.name: "AUKEY WebCam"
Camera.setup: "monocular"
Camera.model: "equirectangular"

Camera.fps: 30.0
Camera.cols: 1920
Camera.rows: 1080
Camera.fx: 2669.328086
Camera.fy: 2607.600518
Camera.cx: 540.743566
Camera.cy: 249.349171
Camera.k1: 0.283600495266156
Camera.k2: 0.13676501661761326
Camera.p1: -0.02359712114118154
Camera.p2: -0.11152650794623843
Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
  - [0.0, 1.0, 0.0, 0.1]
  - [0.0, 1.0, 0.84, 1.0]
  - [0.0, 0.2, 0.7, 1.0]
  - [0.8, 1.0, 0.7, 1.0]
